services:
  auth:
    container_name: auth
    build: ./auth
    volumes:
      - ./auth/code:/code:rw
    ports:
      - "9001:8000"
    networks:
      - backend
    init: true
    restart: on-failure
    env_file:
      - ./auth/.env

  auth-db:
    container_name: auth-db
    build: ./auth-db
    env_file:
      - ./auth-db/.env
    volumes:
      - ./auth-db/data:/var/lib/postgresql/data:rw
    networks:
      - backend
  vault-db:
    container_name: vault-db
    build: ./vault-db
    env_file:
      - ./vault-db/.env
    volumes:
      - ./vault-db/data:/var/lib/postgresql/data:rw
    networks:
      - backend
  vault:
    container_name: vault
    build: ./vault
    volumes:
      - ./vault/data:/vault/file:rw
    networks:
      - backend
    ports:
      - "8200:8200"
    init: true
    restart: on-failure
    env_file:
      - ./vault/.env

networks:
  backend:
    name: backend
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/24
  frontend:
    name: frontend
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/24
