services:
  auth:
    container_name: auth
    build: ./auth
    volumes:
      - ./auth/code:/code:rw
    ports:
      - "9001:8000"
    networks:
      - backend
    init: true
    restart: on-failure
    env_file:
      - ./auth/.env
    secrets:
      - vault_root_token

  auth-db:
    container_name: auth-db
    build: ./auth-db
    env_file:
      - ./auth-db/.env
    volumes:
      - ./auth-db/data:/var/lib/postgresql/data:rw
    networks:
      - backend
    secrets:
      - postgres_user
      - postgres_password
  vault-db:
    container_name: vault-db
    build: ./vault-db
    env_file:
      - ./vault-db/.env
    volumes:
      - ./vault-db/data:/var/lib/postgresql/data:rw
    networks:
      - backend
    secrets:
      - postgres_user
      - postgres_password
  vault:
    container_name: vault
    build: ./vault
    volumes:
      - ./vault/data:/vault/file:rw
      - ./secrets:/vault/secrets:rw
    networks:
      - backend
    ports:
      - "8200:8200"
    init: true
    restart: on-failure
    env_file:
      - ./vault/.env
    secrets:
      - vault_root_token
      - postgres_user
      - postgres_password

networks:
  backend:
    name: backend
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/24
  frontend:
    name: frontend
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/24

secrets:
  vault_root_token:
    file: ./secrets/VAULT_ROOT_TOKEN.txt
  postgres_user:
    file: ./secrets/POSTGRES_USER.txt
  postgres_password:
    file: ./secrets/POSTGRES_PASSWORD.txt
