services:
  python:
    container_name: python
    build: ./python
    volumes:
      - ./code:/code:rw
    networks:
      - ft_transcendence
    init: true
    restart: on-failure
    env_file:
      - ./python/.env
    depends_on:
      - db

  nginx:
    container_name: nginx
    build: ./nginx
    volumes:
      - ./frontend:/frontend:rw
      #- ./code/static:/static:rw
    networks:
      - ft_transcendence
    ports:
      - "8000:443"
    init: true
    restart: on-failure
    env_file:
      - ./nginx/.env
    depends_on:
      - python

  db:
    container_name: db
    build: ./postgres
    env_file:
      - ./postgres/.env
    volumes:
      - ./postgres/data:/var/lib/postgresql/data:rw
    networks:
      - ft_transcendence

networks:
  ft_transcendence:
    name: ft_transcendence
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/24
