# Generated by Django 5.1.2 on 2025-04-05 22:01

import fileUpload.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=fileUpload.models.user_directory_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
