# Generated by Django 5.1.2 on 2025-03-29 23:39

import django.utils.timezone
import fileUpload.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileUpload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profileimage',
            name='image',
            field=models.ImageField(upload_to=fileUpload.models.user_directory_path),
        ),
    ]
