# Generated by Django 5.1.2 on 2024-10-26 13:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcarol', '0002_user_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='losses',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='user',
            name='victories',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Tournments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('init_date', models.DateField()),
                ('duration', models.PositiveIntegerField()),
                ('end_date', models.DateField(editable=False)),
                ('is_active', models.BooleanField(default=False)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tournaments_won', to='appcarol.user')),
            ],
            options={
                'db_table': 'TOURNMENTS',
            },
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_tournment', models.BooleanField(default=False)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games_as_user1', to='appcarol.user')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games_as_user2', to='appcarol.user')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='games_won', to='appcarol.user')),
                ('tournment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tournments', to='appcarol.tournments')),
            ],
            options={
                'db_table': 'GAMES',
            },
        ),
    ]
