# Generated by Django 5.1.2 on 2024-10-26 15:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcarol', '0003_user_is_active_user_losses_user_victories_tournments_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournments',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tournaments_won', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='games',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='games_won', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='games',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games_as_user1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='games',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games_as_user2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('victories', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('losses', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
