# Generated by Django 5.1.2 on 2025-04-05 22:01

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tauxFriendshipStatus',
            fields=[
                ('status', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='tauxGender',
            fields=[
                ('gender', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='tauxPhase',
            fields=[
                ('phase', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='tauxStatus',
            fields=[
                ('statusID', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='tTournaments',
            fields=[
                ('tournament', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('beginDate', models.DateField(blank=True, null=True)),
                ('endDate', models.DateField(blank=True, null=True)),
                ('creationTS', models.DateField()),
                ('createdByUser', models.IntegerField(blank=True, null=True)),
                ('winnerUser', models.IntegerField(blank=True, null=True)),
                ('winnerNick', models.CharField(blank=True, max_length=255, null=True)),
                ('nick1', models.CharField(blank=True, max_length=255, null=True)),
                ('nick2', models.CharField(blank=True, max_length=255, null=True)),
                ('nick3', models.CharField(blank=True, max_length=255, null=True)),
                ('nick4', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cuca.tauxstatus')),
            ],
        ),
        migrations.CreateModel(
            name='tGames',
            fields=[
                ('game', models.AutoField(primary_key=True, serialize=False)),
                ('creationTS', models.DateTimeField(auto_now_add=True)),
                ('startTS', models.DateTimeField(blank=True, null=True)),
                ('endTS', models.DateTimeField(blank=True, null=True)),
                ('user1', models.IntegerField(blank=True, null=True)),
                ('user2', models.IntegerField(blank=True, null=True)),
                ('user1_points', models.IntegerField(blank=True, null=True)),
                ('user2_points', models.IntegerField(blank=True, null=True)),
                ('user1_hits', models.IntegerField(blank=True, null=True)),
                ('user2_hits', models.IntegerField(blank=True, null=True)),
                ('user1_nick', models.CharField(blank=True, max_length=255, null=True)),
                ('user2_nick', models.CharField(blank=True, max_length=255, null=True)),
                ('isLocal', models.BooleanField(default=True)),
                ('isInvitation', models.BooleanField(default=False)),
                ('isInvitAccepted', models.BooleanField(default=False)),
                ('winnerUser', models.IntegerField(blank=True, null=True)),
                ('winnerNick', models.CharField(blank=True, max_length=255, null=True)),
                ('phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cuca.tauxphase')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cuca.tauxstatus')),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cuca.ttournaments')),
            ],
        ),
        migrations.CreateModel(
            name='tUserExtension',
            fields=[
                ('user', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nick', models.CharField(blank=True, max_length=20, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('ulevel', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=5, null=True)),
                ('avatar', models.CharField(default='backk.jpg', max_length=1000)),
                ('bio', models.CharField(blank=True, max_length=2000, null=True)),
                ('lang', models.CharField(default='en', max_length=2)),
                ('gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cuca.tauxgender')),
            ],
        ),
        migrations.CreateModel(
            name='tTournamentUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationTS', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cuca.ttournaments')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cuca.tuserextension')),
            ],
        ),
        migrations.CreateModel(
            name='tFriends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestStatus', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cuca.tauxfriendshipstatus')),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requester', to='cuca.tuserextension')),
                ('user1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='friend1', to='cuca.tuserextension')),
                ('user2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='friend2', to='cuca.tuserextension')),
            ],
        ),
    ]
