# Generated by Django 5.1.2 on 2024-11-13 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournaments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('init_date', models.DateField()),
                ('end_date', models.DateField()),
                ('winner', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user1', models.IntegerField()),
                ('user2', models.IntegerField(blank=True, null=True)),
                ('winner', models.IntegerField(blank=True, null=True)),
                ('istournament', models.BooleanField(default=False)),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cuca.tournaments')),
            ],
        ),
    ]
