# Generated by Django 5.1.3 on 2024-11-18 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tauxGender',
            fields=[
                ('gender', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='tTournaments',
            fields=[
                ('tournament', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('beginDate', models.DateField()),
                ('endDate', models.DateField()),
                ('creationTS', models.DateField()),
                ('createdByUser', models.IntegerField(blank=True, null=True)),
                ('winnerUser', models.IntegerField(blank=True, null=True)),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cuca.tauxstatus')),
            ],
        ),
        migrations.AlterField(
            model_name='tgames',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cuca.ttournaments'),
        ),
        migrations.CreateModel(
            name='tUserExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('birthdate', models.DateField()),
                ('ulevel', models.IntegerField(blank=True, default=0, null=True)),
                ('avatar', models.CharField(blank=True, max_length=1000, null=True)),
                ('victories', models.IntegerField(blank=True, default=0, null=True)),
                ('totalGamesPlayed', models.IntegerField(blank=True, default=0, null=True)),
                ('tVictories', models.IntegerField(blank=True, default=0, null=True)),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cuca.tauxgender')),
            ],
        ),
        migrations.CreateModel(
            name='tTournamentUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationTS', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cuca.ttournaments')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cuca.tuserextension')),
            ],
        ),
        migrations.DeleteModel(
            name='Tournaments',
        ),
    ]
