# Generated by Django 5.1.2 on 2025-04-09 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tgames',
            name='createdByUser',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
