# Generated by Django 5.1.2 on 2024-11-13 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tauxStatus',
            fields=[
                ('statusID', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='tGames',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user1', models.IntegerField()),
                ('user2', models.IntegerField(blank=True, null=True)),
                ('winner', models.IntegerField(blank=True, null=True)),
                ('istournament', models.BooleanField(default=False)),
                ('statusID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cuca.tauxstatus')),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cuca.tournaments')),
            ],
        ),
        migrations.DeleteModel(
            name='Games',
        ),
    ]
