# Generated by Django 5.1.2 on 2024-11-13 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuca', '0002_tauxstatus_tgames_delete_games'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tgames',
            name='statusID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cuca.tauxstatus'),
        ),
    ]
