# Generated by Django 5.1.3 on 2024-11-18 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuca', '0004_ttournaments_alter_tgames_tournament_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tgames',
            old_name='date',
            new_name='creationTS',
        ),
        migrations.RenameField(
            model_name='tgames',
            old_name='id',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='tgames',
            old_name='statusID',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='tgames',
            old_name='winner',
            new_name='winnerUser',
        ),
        migrations.RemoveField(
            model_name='tgames',
            name='istournament',
        ),
    ]
