# Generated by Django 5.1.3 on 2024-11-20 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuca', '0005_rename_date_tgames_creationts_rename_id_tgames_game_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tauxGender',
            fields=[
                ('gender', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='tUserExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('birthdate', models.DateField()),
                ('ulevel', models.IntegerField(blank=True, default=0, null=True)),
                ('avatar', models.CharField(blank=True, max_length=1000, null=True)),
                ('victories', models.IntegerField(blank=True, default=0, null=True)),
                ('totalGamesPlayed', models.IntegerField(blank=True, default=0, null=True)),
                ('tVictories', models.IntegerField(blank=True, default=0, null=True)),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cuca.tauxgender')),
            ],
        ),
        migrations.CreateModel(
            name='tTournamentUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationTS', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cuca.ttournaments')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cuca.tuserextension')),
            ],
        ),
    ]
