# Generated by Django 5.1.4 on 2024-12-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuca', '0006_tauxgender_tuserextension_ttournamentusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='tgames',
            name='isLocal',
            field=models.BooleanField(default=True),
        ),
    ]
