# Generated by Django 5.1.4 on 2024-12-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuca', '0007_tgames_islocal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tuserextension',
            name='id',
        ),
        migrations.AlterField(
            model_name='tuserextension',
            name='user',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
