# Generated by Django 5.1.4 on 2024-12-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuca', '0008_remove_tuserextension_id_alter_tuserextension_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuserextension',
            name='ulevel',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
