# Generated by Django 5.1.4 on 2024-12-14 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuca', '0009_alter_tuserextension_ulevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tgames',
            name='user1',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
