# Generated by Django 5.1.4 on 2024-12-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuca', '0010_alter_tgames_user1'),
    ]

    operations = [
        migrations.CreateModel(
            name='tauxPhase',
            fields=[
                ('phase', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
            ],
        ),
    ]
