# Generated by Django 5.1.4 on 2024-12-14 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuca', '0011_tauxphase'),
    ]

    operations = [
        migrations.AddField(
            model_name='tgames',
            name='phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cuca.tauxphase'),
        ),
    ]
