# Generated by Django 5.1.5 on 2025-01-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuca', '0012_tgames_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuserextension',
            name='bio',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
