# Generated by Django 5.1.5 on 2025-01-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuca', '0013_tuserextension_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuserextension',
            name='nick',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
