# Generated by Django 5.1.5 on 2025-02-03 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuca', '0014_tuserextension_nick'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuserextension',
            name='totalTournPlayed',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
