# Generated by Django 5.1.5 on 2025-02-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuca', '0015_tuserextension_totaltournplayed'),
    ]

    operations = [
        migrations.AddField(
            model_name='tgames',
            name='isInvitAccepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tgames',
            name='isInvitation',
            field=models.BooleanField(default=False),
        ),
    ]
