# Generated by Django 5.1.6 on 2025-02-08 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuca', '0016_tgames_isinvitaccepted_tgames_isinvitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuserextension',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tuserextension',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cuca.tauxgender'),
        ),
    ]
