# Generated by Django 5.1.6 on 2025-02-17 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuca', '0017_alter_tuserextension_birthdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tgames',
            name='user1_hits',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tgames',
            name='user1_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tgames',
            name='user2_hits',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tgames',
            name='user2_points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
