# Generated by Django 5.1.6 on 2025-02-17 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuca', '0018_tgames_user1_hits_tgames_user1_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tgames',
            name='endTS',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
