# Generated by Django 5.1.6 on 2025-02-18 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuca', '0019_tgames_endts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tuserextension',
            name='tVictories',
        ),
        migrations.RemoveField(
            model_name='tuserextension',
            name='totalGamesPlayed',
        ),
        migrations.RemoveField(
            model_name='tuserextension',
            name='totalTournPlayed',
        ),
        migrations.RemoveField(
            model_name='tuserextension',
            name='ulevel',
        ),
        migrations.RemoveField(
            model_name='tuserextension',
            name='victories',
        ),
    ]
