# Generated by Django 5.1.6 on 2025-02-19 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuca', '0021_tuserextension_ulevel'),
    ]

    operations = [
        migrations.CreateModel(
            name='tauxFriendshipStatus',
            fields=[
                ('status', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='tFriends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestStatus', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cuca.tauxfriendshipstatus')),
                ('user1ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='friend1', to='cuca.tuserextension')),
                ('user2ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='friend2', to='cuca.tuserextension')),
            ],
        ),
    ]
