# Generated by Django 5.1.6 on 2025-02-23 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuca', '0022_tauxfriendshipstatus_tfriends'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tfriends',
            old_name='user1ID',
            new_name='user1',
        ),
        migrations.RenameField(
            model_name='tfriends',
            old_name='user2ID',
            new_name='user2',
        ),
        migrations.AddField(
            model_name='tfriends',
            name='requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requester', to='cuca.tuserextension'),
        ),
    ]
