# Generated by Django 5.1.7 on 2025-03-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuca', '0023_rename_user1id_tfriends_user1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tgames',
            name='startTS',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
