# Generated by Django 5.1.7 on 2025-03-24 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuca', '0024_tgames_startts'),
    ]

    operations = [
        migrations.AddField(
            model_name='tgames',
            name='user1_nick',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tgames',
            name='user2_nick',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ttournaments',
            name='nick1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ttournaments',
            name='nick2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ttournaments',
            name='nick3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ttournaments',
            name='nick4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ttournaments',
            name='beginDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ttournaments',
            name='endDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
