# Generated by Django 5.1.7 on 2025-03-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuca', '0025_tgames_user1_nick_tgames_user2_nick_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ttournaments',
            name='winnerNick',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
