# Generated by Django 5.1.7 on 2025-03-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuca', '0026_ttournaments_winnernick'),
    ]

    operations = [
        migrations.AddField(
            model_name='tgames',
            name='winnerNick',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
