# Generated by Django 5.1.7 on 2025-03-29 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuca', '0027_tgames_winnernick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuserextension',
            name='avatar',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
