# Generated by Django 5.1.7 on 2025-03-29 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuca', '0028_alter_tuserextension_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuserextension',
            name='avatar',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
