# Generated by Django 5.1.2 on 2025-04-04 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuca', '0029_alter_tuserextension_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='tauxLanguage',
            fields=[
                ('language', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='tauxgender',
            name='labelES',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tauxgender',
            name='labelFR',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tauxgender',
            name='labelIT',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tauxgender',
            name='labelPT',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tauxphase',
            name='labelES',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tauxphase',
            name='labelFR',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tauxphase',
            name='labelIT',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tauxphase',
            name='labelPT',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tauxstatus',
            name='statusES',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tauxstatus',
            name='statusFR',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tauxstatus',
            name='statusIT',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tauxstatus',
            name='statusPT',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tuserextension',
            name='language',
            field=models.CharField(default='en', max_length=2),
        ),
    ]
