# Generated by Django 5.1.2 on 2024-11-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cucauser',
            name='is_2fa_enabled',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cucauser',
            name='otp_secret',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
