# Generated by Django 5.1.2 on 2024-11-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuca', '0002_cucauser_is_2fa_enabled_cucauser_otp_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cucauser',
            name='otp_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
