# Generated by Django 5.1.2 on 2025-02-26 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuca', '0004_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cucauser',
            name='is_2fa_enabled',
            field=models.IntegerField(default=0),
        ),
    ]
